/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projectpenjualan;
import java.sql.*;
import java.util.HashMap;
import javax.swing.table.*;
//import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import projectpenjualan.UserSession;
/**
 *
 * @author Lenovo G-40
 */
public class InputDataKonsumen extends javax.swing.JFrame {
DefaultTableModel tabel;
ResultSet rs=null;
    /**
     * Creates new form InputDataKonsumen
     */

    public InputDataKonsumen() {
        initComponents();
        TxtNamaKonsumen.requestFocus();
        tampil_data();
        kosong();
        idkonsumen();
    }
    
     private void kosong(){
        //TxtIdPelanggan.setText(null);
        TxtNamaKonsumen.setText(null);
        TxtAlamat.setText(null);
        TxtNoTelp.setText(null);  
    } 
     
     private void idkonsumen()
    {
       try {
            java.sql.Connection conn =(java.sql.Connection)Koneksi.koneksiDB();
            String sql ="SELECT * FROM konsumen ORDER BY idkonsumen DESC";
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery(sql);
            if (rs.next()) {
                String idkonsumen= rs.getString("idkonsumen").substring(1);
                String AN = "" + (Integer.parseInt(idkonsumen) + 1);
                String Nol = "";

                if(AN.length()==1)
                {Nol = "00";}
                else if(AN.length()==2)
                {Nol = "0";}
                else if(AN.length()==3)
                {Nol = "";}

               TxtIdKonsumen.setText("K" + Nol + AN);
            } else {
               TxtIdKonsumen.setText("K001");
            }

           }catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
           }
     }
     
     public void tampil_data(){
        DefaultTableModel tabel=new DefaultTableModel();
        tabel.addColumn("Id Konsumen");
        tabel.addColumn("Nama Konsumen");
        tabel.addColumn("Alamat");
        tabel.addColumn("No.Telp");
        try{
            java.sql.Connection conn =(java.sql.Connection)Koneksi.koneksiDB();
            String sql = "SELECT * FROM konsumen";
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery(sql);
            while(rs.next())
            {
                tabel.addRow(new Object[]{
                    rs.getString(1),
                    rs.getString(2),
                    rs.getString(3),
                    rs.getString(4)});
            }
            TableDataKonsumen.setModel(tabel);
        }
        catch (Exception e){
        }
    }
    
    private void cariData(String key){
        try{
            Object[] judul_kolom = {"Id Konsumen", 
                "Nama Konsumen", 
                "Alamat", 
                "No.Telp"};
            tabel=new DefaultTableModel(null,judul_kolom);
            TableDataKonsumen.setModel(tabel);
            
            Connection conn=(Connection)Koneksi.koneksiDB();
            Statement stt=conn.createStatement();
            tabel.getDataVector().removeAllElements();
            
            rs=stt.executeQuery("SELECT * FROM konsumen WHERE idkonsumen "
                    + "LIKE '%"+key+"%' OR namakonsumen LIKE '%"+key+"%'");  
            while(rs.next()){
                Object[] data={
                    rs.getString("idkonsumen"),
                    rs.getString("namakonsumen"),
                    rs.getString("alamat"),
                    rs.getString("notelp")         
                };
               tabel.addRow(data);
            }                
        } catch (Exception ex) {
        System.err.println(ex.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        TxtIdKonsumen = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TxtNoTelp = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        TxtNamaKonsumen = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TxtCariDataKonsumen = new javax.swing.JTextField();
        BtnTambah = new javax.swing.JButton();
        BtnSimpan = new javax.swing.JButton();
        BtnHapus = new javax.swing.JButton();
        BtnUpdate = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableDataKonsumen = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        TxtAlamat = new javax.swing.JTextArea();
        BtnMenu = new javax.swing.JButton();
        BtnCetak = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText(" INPUT DATA KONSUMEN");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 16, 322, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("ID KONSUMEN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 56, -1, 36));

        TxtIdKonsumen.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TxtIdKonsumen.setEnabled(false);
        TxtIdKonsumen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtIdKonsumenActionPerformed(evt);
            }
        });
        getContentPane().add(TxtIdKonsumen, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 63, 147, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("ALAMAT");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 56, -1, 36));
        getContentPane().add(TxtNoTelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(454, 181, 147, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("NOTELP");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 174, -1, 36));

        TxtNamaKonsumen.setText(" ");
        TxtNamaKonsumen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNamaKonsumenActionPerformed(evt);
            }
        });
        getContentPane().add(TxtNamaKonsumen, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 105, 147, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("NAMA KONSUMEN");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 98, -1, 36));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("CARI DATA KONSUMEN");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 231, -1, 36));

        TxtCariDataKonsumen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCariDataKonsumenActionPerformed(evt);
            }
        });
        TxtCariDataKonsumen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtCariDataKonsumenKeyReleased(evt);
            }
        });
        getContentPane().add(TxtCariDataKonsumen, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 238, 146, -1));

        BtnTambah.setText("Tambah");
        BtnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTambahActionPerformed(evt);
            }
        });
        getContentPane().add(BtnTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 273, -1, -1));

        BtnSimpan.setText("Simpan");
        BtnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSimpanActionPerformed(evt);
            }
        });
        getContentPane().add(BtnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 273, -1, -1));

        BtnHapus.setText("Hapus");
        BtnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHapusActionPerformed(evt);
            }
        });
        getContentPane().add(BtnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 273, -1, -1));

        BtnUpdate.setText("Update");
        BtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(BtnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(353, 273, -1, -1));

        TableDataKonsumen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TableDataKonsumen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableDataKonsumenMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TableDataKonsumen);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 319, 566, 123));

        TxtAlamat.setColumns(20);
        TxtAlamat.setRows(5);
        jScrollPane1.setViewportView(TxtAlamat);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(454, 56, -1, 100));

        BtnMenu.setText("Menu");
        BtnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMenuActionPerformed(evt);
            }
        });
        getContentPane().add(BtnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(509, 273, -1, -1));

        BtnCetak.setText("Cetak");
        BtnCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCetakActionPerformed(evt);
            }
        });
        getContentPane().add(BtnCetak, new org.netbeans.lib.awtextra.AbsoluteConstraints(431, 273, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon("D:\\Tugas Java\\ProjectPBO\\ProjectPenjualan\\images\\screenshot-1705742430633.png")); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 470));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TxtIdKonsumenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtIdKonsumenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtIdKonsumenActionPerformed

    private void TxtNamaKonsumenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNamaKonsumenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNamaKonsumenActionPerformed

    private void TxtCariDataKonsumenKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtCariDataKonsumenKeyReleased
        // TODO add your handling code here:/
        //cari data
        String key=TxtCariDataKonsumen.getText();
        System.out.println(key);

        if(key!=""){
            cariData(key);
        }else{
            tampil_data();
        }
    }//GEN-LAST:event_TxtCariDataKonsumenKeyReleased

    private void BtnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTambahActionPerformed
        // TODO add your handling code here:
        TxtNamaKonsumen.requestFocus();
        kosong();
        idkonsumen();
    }//GEN-LAST:event_BtnTambahActionPerformed

    private void BtnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSimpanActionPerformed
        // TODO add your handling code here:
        // fungsi simpan data
        try{
            String sql = "INSERT INTO konsumen VALUES('"
            +TxtIdKonsumen.getText()+"','"
            +TxtNamaKonsumen.getText()+"','"
            +TxtAlamat.getText()+"','"
            +TxtNoTelp.getText()+"')";
            java.sql.Connection conn =(java.sql.Connection)Koneksi.koneksiDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null , "Data Konsumen Berhasil Di Simpan !");
            tampil_data();
            kosong();
            idkonsumen();
            TxtNamaKonsumen.requestFocus();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Data Konsumen Gagal Di Simpan !");
            System.out.print(e.getMessage());
        }
    }//GEN-LAST:event_BtnSimpanActionPerformed

    private void BtnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHapusActionPerformed
        // TODO add your handling code here:
        // fungsi hapus data
        try {
            String sql ="DELETE FROM konsumen WHERE idkonsumen='"+TxtIdKonsumen.getText()+"'";
            java.sql.Connection conn=(Connection)Koneksi.koneksiDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(this, "Data Konsumen Berhasil Di Hapus !");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        tampil_data();
        kosong();
    }//GEN-LAST:event_BtnHapusActionPerformed

    private void BtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUpdateActionPerformed
        // TODO add your handling code here:
        // Edit Data
        try {
            String sql ="UPDATE konsumen SET "
            + "namakonsumen = '"+TxtNamaKonsumen.getText()+"', "
            + "alamat= '"+TxtAlamat.getText()+"', "
            + "notelp= '"+TxtNoTelp.getText()+"' "
            + "WHERE idkonsumen= '"+TxtIdKonsumen.getText()+"'";
            java.sql.Connection conn=(Connection)Koneksi.koneksiDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Data Konsumen Berhasil Di Update !");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Update Data Konsumen Gagal"+e.getMessage());
        }
        tampil_data();
    }//GEN-LAST:event_BtnUpdateActionPerformed

    private void TableDataKonsumenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableDataKonsumenMouseClicked
        // TODO add your handling code here:
        // menampilkan data kedalam form pengisian:
        int baris = TableDataKonsumen.rowAtPoint(evt.getPoint());
        String idkonsumen =TableDataKonsumen.getValueAt(baris, 0).toString();
        TxtIdKonsumen.setText(idkonsumen);
        String namakonsumen = TableDataKonsumen.getValueAt(baris,1).toString();
        TxtNamaKonsumen.setText(namakonsumen);
        String alamat = TableDataKonsumen.getValueAt(baris, 2).toString();
        TxtAlamat.setText(alamat);
        String notelp= TableDataKonsumen.getValueAt(baris, 3).toString();
        TxtNoTelp.setText(notelp);
    }//GEN-LAST:event_TableDataKonsumenMouseClicked

    private void TxtCariDataKonsumenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCariDataKonsumenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCariDataKonsumenActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formComponentShown

    private void BtnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMenuActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_BtnMenuActionPerformed

    private void BtnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCetakActionPerformed
        // TODO add your handling code here:
        try {
           HashMap hash = new HashMap();
           hash.put("username", UserSession.getUserPengguna());
           JasperPrint jp = JasperFillManager.fillReport
        (getClass().getResourceAsStream("ReportDataKonsumen.jasper"),hash,Koneksi.koneksiDB());
           JasperViewer.viewReport(jp, false);
        } catch(Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_BtnCetakActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InputDataKonsumen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InputDataKonsumen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InputDataKonsumen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InputDataKonsumen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InputDataKonsumen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCetak;
    private javax.swing.JButton BtnHapus;
    private javax.swing.JButton BtnMenu;
    private javax.swing.JButton BtnSimpan;
    private javax.swing.JButton BtnTambah;
    private javax.swing.JButton BtnUpdate;
    private javax.swing.JTable TableDataKonsumen;
    private javax.swing.JTextArea TxtAlamat;
    private javax.swing.JTextField TxtCariDataKonsumen;
    private javax.swing.JTextField TxtIdKonsumen;
    private javax.swing.JTextField TxtNamaKonsumen;
    private javax.swing.JTextField TxtNoTelp;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
