/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projectpenjualan;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author admin
 */
public class ManajemenUser extends javax.swing.JFrame {
DefaultTableModel tabel;
ResultSet rs=null;
    /**
     * Creates new form ManajemenUser
     */
    public ManajemenUser() {
        initComponents();
        TxtNamaKelola.requestFocus();
        tampil_data();
    }
    
     private void kosong(){
        TxtNamaKelola.setText(null);
        TxtUserName.setText(null);
        TxtPassword.setText(null);  
        RBGroup.clearSelection();
    } 
    
     public void tampil_data(){
        DefaultTableModel tabel=new DefaultTableModel();
        tabel.addColumn("Pengguna");
        tabel.addColumn("Username");
        tabel.addColumn("Password");
        tabel.addColumn("Hak Akses");
        try{
            java.sql.Connection conn =(java.sql.Connection)Koneksi.koneksiDB();
            String sql = "SELECT * FROM manajemenuser";
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery(sql);
            while(rs.next())
            {
                tabel.addRow(new Object[]{
                    rs.getString(1),
                    rs.getString(2),
                    rs.getString(3),
                    rs.getString(4)});
            }
            TableDataUser.setModel(tabel);
        }
        catch (Exception e){
        }
    }
     
     private void cariData(String key){
        try{
            Object[] judul_kolom = {"Pengguna", 
                "Username", 
                "Password", 
                "Hak Akses"};
            tabel=new DefaultTableModel(null,judul_kolom);
            TableDataUser.setModel(tabel);
            
            Connection conn=(Connection)Koneksi.koneksiDB();
            Statement stt=conn.createStatement();
            tabel.getDataVector().removeAllElements();
            
            rs=stt.executeQuery("SELECT * FROM manajemenuser WHERE username "
                    + "LIKE '%"+key+"%' OR  pengguna LIKE '%"+key+"%'");  
            while(rs.next()){
                Object[] data={
                    rs.getString("pengguna"),
                    rs.getString("username"),
                    rs.getString("password"),
                    rs.getString("hakakses")         
                };
               tabel.addRow(data);
            }                
        } catch (Exception ex) {
        System.err.println(ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RBGroup = new javax.swing.ButtonGroup();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TxtCariDataUser = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        BtnTambah = new javax.swing.JButton();
        BtnSimpan = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        BtnHapus = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        BtnUpdate = new javax.swing.JButton();
        TxtNamaKelola = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableDataUser = new javax.swing.JTable();
        TxtUserName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        BtnMenu = new javax.swing.JButton();
        TxtPassword = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        JRAdmin = new javax.swing.JRadioButton();
        JRKasir = new javax.swing.JRadioButton();
        JRPemilik = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("USERNAME");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 110, -1, 36));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("PASSWORD");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 68, -1, 36));

        TxtCariDataUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCariDataUserActionPerformed(evt);
            }
        });
        TxtCariDataUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtCariDataUserKeyReleased(evt);
            }
        });
        getContentPane().add(TxtCariDataUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 207, 146, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("CARI DATA USER");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 200, -1, 36));

        BtnTambah.setText("Tambah");
        BtnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTambahActionPerformed(evt);
            }
        });
        getContentPane().add(BtnTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 254, -1, -1));

        BtnSimpan.setText("Simpan");
        BtnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSimpanActionPerformed(evt);
            }
        });
        getContentPane().add(BtnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 254, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("MANAJEMEN USER");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 6, -1, 48));

        BtnHapus.setText("Hapus");
        BtnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHapusActionPerformed(evt);
            }
        });
        getContentPane().add(BtnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 254, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("NAMA KELOLA");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 68, -1, 36));

        BtnUpdate.setText("Update");
        BtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(BtnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 254, -1, -1));

        TxtNamaKelola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNamaKelolaActionPerformed(evt);
            }
        });
        getContentPane().add(TxtNamaKelola, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 75, 147, -1));

        TableDataUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TableDataUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableDataUserMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TableDataUser);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 294, 521, 123));

        TxtUserName.setText(" ");
        TxtUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtUserNameActionPerformed(evt);
            }
        });
        getContentPane().add(TxtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 117, 147, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("HAK AKSES");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 110, -1, 36));

        BtnMenu.setText("Menu");
        BtnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMenuActionPerformed(evt);
            }
        });
        getContentPane().add(BtnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(422, 254, -1, -1));
        getContentPane().add(TxtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(402, 75, 138, -1));

        RBGroup.add(JRAdmin);
        JRAdmin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        JRAdmin.setText("Admin");
        JRAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRAdminActionPerformed(evt);
            }
        });

        RBGroup.add(JRKasir);
        JRKasir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        JRKasir.setText("Kasir");
        JRKasir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRKasirActionPerformed(evt);
            }
        });

        RBGroup.add(JRPemilik);
        JRPemilik.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        JRPemilik.setText("Pemilik");
        JRPemilik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRPemilikActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JRAdmin)
                    .addComponent(JRPemilik)
                    .addComponent(JRKasir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JRAdmin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JRKasir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JRPemilik)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(401, 110, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon("D:\\Tugas Java\\ProjectPBO\\ProjectPenjualan\\images\\screenshot-1705742430633.png")); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 440));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TxtCariDataUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCariDataUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCariDataUserActionPerformed

    private void TxtCariDataUserKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtCariDataUserKeyReleased
        // TODO add your handling code here:/
        //cari data
        String key=TxtCariDataUser.getText();
        System.out.println(key);

        if(key!=""){
            cariData(key);
        }else{
            tampil_data();
        }
    }//GEN-LAST:event_TxtCariDataUserKeyReleased

    private void BtnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTambahActionPerformed
        // TODO add your handling code here:
        TxtNamaKelola.requestFocus();
        kosong();
    }//GEN-LAST:event_BtnTambahActionPerformed

    
    
    private void BtnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSimpanActionPerformed
        // TODO add your handling code here:
        // fungsi simpan data
   
        
        String hakakses = null;
        if(JRAdmin.isSelected()){
            hakakses="Admin";
        }
        else if(JRAdmin.isSelected()){
            hakakses="Kassir";
        }
            else{
            hakakses="Pemilik";
        }
        try{
            String sql = "INSERT INTO manajemenuser VALUES('"
            +TxtNamaKelola.getText()+"','"
            +TxtUserName.getText()+"'"
            + ",MD5('"+String.valueOf(TxtPassword.getPassword())+"'),'"
            +hakakses+"')";
            java.sql.Connection conn =(java.sql.Connection)Koneksi.koneksiDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null , "Registrasi Berhasil !");
            tampil_data();
            kosong();
            TxtNamaKelola.requestFocus();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Registrasi Gagal !");
            System.out.print(e.getMessage());
        }
    }//GEN-LAST:event_BtnSimpanActionPerformed

    private void BtnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHapusActionPerformed
        // TODO add your handling code here:
        // fungsi hapus data
        try {
            String sql ="DELETE FROM manajemenuser WHERE username='"+TxtUserName.getText()+"'";
            java.sql.Connection conn=(Connection)Koneksi.koneksiDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(this, "Data User Di Drop !");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        tampil_data();
        kosong();
        TxtNamaKelola.requestFocus();
    }//GEN-LAST:event_BtnHapusActionPerformed

    private void BtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUpdateActionPerformed
        // TODO add your handling code here:
        // Edit Data
        String hakakses = null;
        if(JRAdmin.isSelected()){
            hakakses="Admin";
        }
        else if(JRAdmin.isSelected()){
            hakakses="Kassir";
        }
            else{
            hakakses="Pemilik";
        }
        try {
            String sql ="UPDATE manajemenuser SET "
            + "pengguna = '"+TxtNamaKelola.getText()+"', "
            + "password = MD5('"+String.valueOf(TxtPassword.getPassword())+"'),"
            + "hakakses= '"+hakakses+"' "
            + "WHERE username= '"+TxtUserName.getText()+"'";
            java.sql.Connection conn=(Connection)Koneksi.koneksiDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Data User Di Update !");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Update Data User Gagal"+e.getMessage());
        }
        tampil_data();
    }//GEN-LAST:event_BtnUpdateActionPerformed

    private void TxtNamaKelolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNamaKelolaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNamaKelolaActionPerformed

    private void TableDataUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableDataUserMouseClicked
        // TODO add your handling code here:
        // menampilkan data kedalam form pengisian:
        int baris = TableDataUser.rowAtPoint(evt.getPoint());
        String pengguna =TableDataUser.getValueAt(baris, 0).toString();
        TxtNamaKelola.setText(pengguna);
        String username = TableDataUser.getValueAt(baris,1).toString();
        TxtUserName.setText(username);
        String password = TableDataUser.getValueAt(baris, 2).toString();
        TxtPassword.setText(password);
        if("Admin".equals(TableDataUser.getValueAt(baris,3).toString())){
            JRAdmin.setSelected(true);
    }
        else if("Kasir".equals(TableDataUser.getValueAt(baris,3).toString())){
            JRKasir.setSelected(true);
    }
        else{
            JRKasir.setSelected(true);
    }
        
    }//GEN-LAST:event_TableDataUserMouseClicked

    private void TxtUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtUserNameActionPerformed

    private void BtnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMenuActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_BtnMenuActionPerformed

    private void JRAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JRAdminActionPerformed

    private void JRKasirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRKasirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JRKasirActionPerformed

    private void JRPemilikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRPemilikActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JRPemilikActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManajemenUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManajemenUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManajemenUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManajemenUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManajemenUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnHapus;
    private javax.swing.JButton BtnMenu;
    private javax.swing.JButton BtnSimpan;
    private javax.swing.JButton BtnTambah;
    private javax.swing.JButton BtnUpdate;
    private javax.swing.JRadioButton JRAdmin;
    private javax.swing.JRadioButton JRKasir;
    private javax.swing.JRadioButton JRPemilik;
    private javax.swing.ButtonGroup RBGroup;
    private javax.swing.JTable TableDataUser;
    private javax.swing.JTextField TxtCariDataUser;
    private javax.swing.JTextField TxtNamaKelola;
    private javax.swing.JPasswordField TxtPassword;
    private javax.swing.JTextField TxtUserName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
