/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package projectpenjualan;

import config.Background;
/**
 *
 * @author admin
 */
public class Menu extends javax.swing.JFrame {

 private void userLogin(){
    LblUserLogin.setText(UserSession.getUserLogin());
    }
 
  private void userPengguna(){
    LblKelola.setText(UserSession.getUserPengguna());
    }
  
    
    private void hakakses() {
     String user=LblUserLogin.getText();
      String pengguna=LblKelola.getText();
        if(user.equals("Admin")){
       
        Master.setEnabled(true);
        Transaksi.setEnabled(false);
        Laporan.setEnabled(false);
        Pengaturan.setEnabled(true);
        }
        else  if(user.equals("Kasir")){
       
        Master.setEnabled(false);
        Transaksi.setEnabled(true);
        Laporan.setEnabled(false);
        Pengaturan.setEnabled(false);
        }
        else {
        
        Master.setEnabled(false);
        Transaksi.setEnabled(false);
        Laporan.setEnabled(true);
        Pengaturan.setEnabled(false);
         }
        }
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        userLogin();
        userPengguna();
        hakakses();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new Background();
        LblUserLogin = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        LblKelola = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        Master = new javax.swing.JMenu();
        DataBarang = new javax.swing.JMenuItem();
        DataKonsumen = new javax.swing.JMenuItem();
        Transaksi = new javax.swing.JMenu();
        Penjualan = new javax.swing.JMenuItem();
        Laporan = new javax.swing.JMenu();
        LaporanPerTanggal = new javax.swing.JMenuItem();
        Pengaturan = new javax.swing.JMenu();
        ManajemenUser = new javax.swing.JMenuItem();
        LogOut = new javax.swing.JMenu();
        Exit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LblUserLogin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        desktopPane.add(LblUserLogin);
        LblUserLogin.setBounds(60, 30, 110, 20);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Status :");
        desktopPane.add(jLabel3);
        jLabel3.setBounds(0, 30, 70, 20);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Kelola :");
        desktopPane.add(jLabel4);
        jLabel4.setBounds(0, 0, 70, 20);

        LblKelola.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        desktopPane.add(LblKelola);
        LblKelola.setBounds(60, 0, 110, 20);

        Master.setMnemonic('f');
        Master.setText("Master");

        DataBarang.setMnemonic('o');
        DataBarang.setText("Data Barang");
        DataBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DataBarangActionPerformed(evt);
            }
        });
        Master.add(DataBarang);

        DataKonsumen.setMnemonic('s');
        DataKonsumen.setText("Data Konsumen");
        DataKonsumen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DataKonsumenActionPerformed(evt);
            }
        });
        Master.add(DataKonsumen);

        menuBar.add(Master);

        Transaksi.setMnemonic('e');
        Transaksi.setText("Transaksi");

        Penjualan.setMnemonic('t');
        Penjualan.setText("Penjualan");
        Penjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PenjualanActionPerformed(evt);
            }
        });
        Transaksi.add(Penjualan);

        menuBar.add(Transaksi);

        Laporan.setText("Laporan");

        LaporanPerTanggal.setText("Laporan Penjualan Per/Tanggal");
        LaporanPerTanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LaporanPerTanggalActionPerformed(evt);
            }
        });
        Laporan.add(LaporanPerTanggal);

        menuBar.add(Laporan);

        Pengaturan.setMnemonic('h');
        Pengaturan.setText("Pengaturan");

        ManajemenUser.setMnemonic('c');
        ManajemenUser.setText("Manajemen User");
        ManajemenUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManajemenUserActionPerformed(evt);
            }
        });
        Pengaturan.add(ManajemenUser);

        menuBar.add(Pengaturan);

        LogOut.setText("Log Out");

        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        LogOut.add(Exit);

        menuBar.add(LogOut);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 527, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DataKonsumenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DataKonsumenActionPerformed
        // TODO add your handling code here:
        new InputDataKonsumen().setVisible(true);
    }//GEN-LAST:event_DataKonsumenActionPerformed

    private void DataBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DataBarangActionPerformed
        // TODO add your handling code here:
        new InputDataBarang().setVisible(true);
    }//GEN-LAST:event_DataBarangActionPerformed

    private void PenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PenjualanActionPerformed
        // TODO add your handling code here:
        new Penjualan().setVisible(true);
    }//GEN-LAST:event_PenjualanActionPerformed

    private void LaporanPerTanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LaporanPerTanggalActionPerformed
        // TODO add your handling code here:
        new CetakLaporanPenjualanPerTanggal().setVisible(true);
    }//GEN-LAST:event_LaporanPerTanggalActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ExitActionPerformed

    private void ManajemenUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManajemenUserActionPerformed
        // TODO add your handling code here:
         new ManajemenUser().setVisible(true);
    }//GEN-LAST:event_ManajemenUserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem DataBarang;
    private javax.swing.JMenuItem DataKonsumen;
    private javax.swing.JMenuItem Exit;
    private javax.swing.JMenu Laporan;
    private javax.swing.JMenuItem LaporanPerTanggal;
    private javax.swing.JLabel LblKelola;
    private javax.swing.JLabel LblUserLogin;
    private javax.swing.JMenu LogOut;
    private javax.swing.JMenuItem ManajemenUser;
    private javax.swing.JMenu Master;
    private javax.swing.JMenu Pengaturan;
    private javax.swing.JMenuItem Penjualan;
    private javax.swing.JMenu Transaksi;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
