/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projectpenjualan;
import java.sql.*;
import javax.swing.table.*;
//import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
/**
 *
 * @author Lenovo G-40
 */
public class ModalDataBarang extends javax.swing.JFrame {
DefaultTableModel tabel;
ResultSet rs=null;

public Penjualan brg = null;
    /**
     * Creates new form ModalDataBarang
     */
    public ModalDataBarang() {
        initComponents();
        tampil_data();
    }
    
     public void tampil_data(){
        DefaultTableModel tabel=new DefaultTableModel();
        tabel.addColumn("Kode Barang");
        tabel.addColumn("Nama Barang");
        tabel.addColumn("Stock");
        tabel.addColumn("Harga");
        try{
            java.sql.Connection conn =(java.sql.Connection)Koneksi.koneksiDB();
            String sql = "SELECT * FROM barang";
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery(sql);
            
            while(rs.next())
            {
                tabel.addRow(new Object[]{
                    rs.getString(1),
                    rs.getString(2),
                    rs.getString(3),
                    rs.getString(4)});
            }
            TableDataBarang.setModel(tabel);
        }
        catch (Exception e){
        }
    }
    
    private void cariData(String key){
        try{
            Object[] judul_kolom = {"Kode Barang", 
                "Nama Barang", 
                "Stock", 
                "Harga"};
            tabel=new DefaultTableModel(null,judul_kolom);
            TableDataBarang.setModel(tabel);
            
            Connection conn=(Connection)Koneksi.koneksiDB();
            Statement stt=conn.createStatement();
            tabel.getDataVector().removeAllElements();
            
            rs=stt.executeQuery("SELECT * FROM barang WHERE kdbarang "
                    + "LIKE '%"+key+"%' OR namabarang LIKE '%"+key+"%'");  
            while(rs.next()){
                Object[] data={
                    rs.getString("kdbarang"),
                    rs.getString("namabarang"),
                    rs.getString("stock"),
                    rs.getString("harga")         
                };
               tabel.addRow(data);
            }                
        } catch (Exception ex) {
        System.err.println(ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnKeluarCariKonsumen1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableDataBarang = new javax.swing.JTable();
        TxtCariDataBarang = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        BtnKeluarCariBarang = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        BtnKeluarCariKonsumen1.setText("Keluar");
        BtnKeluarCariKonsumen1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKeluarCariKonsumen1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TableDataBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TableDataBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableDataBarangMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TableDataBarang);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 509, 123));

        TxtCariDataBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCariDataBarangActionPerformed(evt);
            }
        });
        TxtCariDataBarang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtCariDataBarangKeyReleased(evt);
            }
        });
        getContentPane().add(TxtCariDataBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 43, 146, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("CARI DATA BARANG");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 36, -1, 36));

        BtnKeluarCariBarang.setText("Keluar");
        BtnKeluarCariBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKeluarCariBarangActionPerformed(evt);
            }
        });
        getContentPane().add(BtnKeluarCariBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 43, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon("D:\\Tugas Java\\ProjectPBO\\ProjectPenjualan\\images\\screenshot-1705742430633.png")); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 250));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TableDataBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableDataBarangMouseClicked
        // TODO add your handling code here:
        // menampilkan data kedalam form pengisian:
        int index = TableDataBarang.getSelectedRow();
        brg.kdbarang= TableDataBarang.getValueAt(index, 0).toString();
        brg.namabarang = TableDataBarang.getValueAt(index, 1).toString();
        brg.harga = TableDataBarang.getValueAt(index, 3).toString();
        brg.BarangTerpilih();
        this.dispose();
    }//GEN-LAST:event_TableDataBarangMouseClicked

    private void TxtCariDataBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCariDataBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCariDataBarangActionPerformed

    private void TxtCariDataBarangKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtCariDataBarangKeyReleased
        // TODO add your handling code here:/
        //cari data
        String key=TxtCariDataBarang.getText();
        System.out.println(key);

        if(key!=""){
            cariData(key);
        }else{
            tampil_data();
        }
    }//GEN-LAST:event_TxtCariDataBarangKeyReleased

    private void BtnKeluarCariBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKeluarCariBarangActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_BtnKeluarCariBarangActionPerformed

    private void BtnKeluarCariKonsumen1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKeluarCariKonsumen1ActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_BtnKeluarCariKonsumen1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModalDataBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModalDataBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModalDataBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModalDataBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModalDataBarang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnKeluarCariBarang;
    private javax.swing.JButton BtnKeluarCariKonsumen1;
    private javax.swing.JTable TableDataBarang;
    private javax.swing.JTextField TxtCariDataBarang;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
