/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projectpenjualan;
import java.sql.*;
import javax.swing.table.*;
//import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
/**
 *
 * @author Lenovo G-40
 */
public class ModalDataKonsumen extends javax.swing.JFrame {
DefaultTableModel tabel;
ResultSet rs=null;

public Penjualan ksm = null;

    /**
     * Creates new form ModalDataKonsumen
     */
    public ModalDataKonsumen() {
        initComponents();
        tampil_data();
    }
    
    
     public void tampil_data(){
        DefaultTableModel tabel=new DefaultTableModel();
        tabel.addColumn("Id Konsumen");
        tabel.addColumn("Nama Konsumen");
        tabel.addColumn("Alamat");
        tabel.addColumn("No.Telp");
        try{
            java.sql.Connection conn =(java.sql.Connection)Koneksi.koneksiDB();
            String sql = "SELECT * FROM konsumen";
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery(sql);
            while(rs.next())
            {
                tabel.addRow(new Object[]{
                    rs.getString(1),
                    rs.getString(2),
                    rs.getString(3),
                    rs.getString(4)});
            }
            TableDataKonsumen.setModel(tabel);
        }
        catch (Exception e){
        }
    }
    
    private void cariData(String key){
        try{
            Object[] judul_kolom = {"Id Konsumen", 
                "Nama Konsumen", 
                "Alamat", 
                "No.Telp"};
            tabel=new DefaultTableModel(null,judul_kolom);
            TableDataKonsumen.setModel(tabel);
            
            Connection conn=(Connection)Koneksi.koneksiDB();
            Statement stt=conn.createStatement();
            tabel.getDataVector().removeAllElements();
            
            rs=stt.executeQuery("SELECT * FROM konsumen WHERE idkonsumen "
                    + "LIKE '%"+key+"%' OR namakonsumen LIKE '%"+key+"%'");  
            while(rs.next()){
                Object[] data={
                    rs.getString("idkonsumen"),
                    rs.getString("namakonsumen"),
                    rs.getString("alamat"),
                    rs.getString("notelp")         
                };
               tabel.addRow(data);
            }                
        } catch (Exception ex) {
        System.err.println(ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        TxtCariDataKonsumen = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableDataKonsumen = new javax.swing.JTable();
        BtnKeluarCariKonsumen = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("CARI DATA KONSUMEN");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 38, -1, 36));

        TxtCariDataKonsumen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCariDataKonsumenActionPerformed(evt);
            }
        });
        TxtCariDataKonsumen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtCariDataKonsumenKeyReleased(evt);
            }
        });
        getContentPane().add(TxtCariDataKonsumen, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 45, 146, -1));

        TableDataKonsumen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TableDataKonsumen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableDataKonsumenMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TableDataKonsumen);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 92, 566, 123));

        BtnKeluarCariKonsumen.setText("Keluar");
        BtnKeluarCariKonsumen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKeluarCariKonsumenActionPerformed(evt);
            }
        });
        getContentPane().add(BtnKeluarCariKonsumen, new org.netbeans.lib.awtextra.AbsoluteConstraints(327, 45, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon("D:\\Tugas Java\\ProjectPBO\\ProjectPenjualan\\images\\screenshot-1705742430633.png")); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 240));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TxtCariDataKonsumenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCariDataKonsumenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCariDataKonsumenActionPerformed

    private void TxtCariDataKonsumenKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtCariDataKonsumenKeyReleased
        // TODO add your handling code here:/
        //cari data
        String key=TxtCariDataKonsumen.getText();
        System.out.println(key);

        if(key!=""){
            cariData(key);
        }else{
            tampil_data();
        }
    }//GEN-LAST:event_TxtCariDataKonsumenKeyReleased

    private void TableDataKonsumenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableDataKonsumenMouseClicked
        // TODO add your handling code here:
        // menampilkan data kedalam form pengisian:
        int index = TableDataKonsumen.getSelectedRow();
        ksm.idkonsumen= TableDataKonsumen.getValueAt(index, 0).toString();
        ksm.namakonsumen = TableDataKonsumen.getValueAt(index, 1).toString();
        ksm.KonsumenTerpilih();
        this.dispose();
    }//GEN-LAST:event_TableDataKonsumenMouseClicked

    private void BtnKeluarCariKonsumenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKeluarCariKonsumenActionPerformed
        // TODO add your handling code here:
       this.dispose();
    }//GEN-LAST:event_BtnKeluarCariKonsumenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModalDataKonsumen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModalDataKonsumen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModalDataKonsumen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModalDataKonsumen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModalDataKonsumen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnKeluarCariKonsumen;
    private javax.swing.JTable TableDataKonsumen;
    private javax.swing.JTextField TxtCariDataKonsumen;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
